### ISSUE TITLE
Steps on Creating RAC?

### ISSUE THREAD

**Issue by completelybatty** [hajee/ora_rac#3]
I wanted to test some of the features and having GI already installed, wanted to see if I could install RAC using ora_rac.  So, would the steps be something like the following:

site.pp
# Set params here:
ora_rac::params (...)
# Create the master
ora_rac::db_master
# Create the second server
ora::db_server
# Start the instances
ora_rac::ora_instance

--
mohammed

**Comment by hajee** [comment]
Mohammed,

You are completely right. Like I said in the mail, we are working on a complete overhaul of this module. After we are finished, we will work on the documentation. This is certainly one of the points we will look at.

Regards

**Comment by completelybatty** [comment]
Thanks.  I will try it and see what happens.  BTW, this is on RHEL 6.5

**Comment by completelybatty** [comment]
Hi Bert,

Ok, so looks like I need to do something with assert_type.  When I run puppet agent -t -noop, I get the following error:
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Unknown function assert_type at /etc/puppet/modules/ora_rac/manifests/params.pp:38

And line 38 in params.pp is:
assert_type(String[1,8], $db_name)              |$e, $a| { fail "dbname is ${a}, but must be between 1 and 8 character length string" }

So, looks like I have to do something with assert_type.rb from here:
https://github.com/hajee/backport/blob/master/lib/puppet/parser/functions/assert_type.rb

Looks like I'm using 3.4.2 and according to the docs here: https://github.com/hajee/backport, it looks like 3.6 is the lowest version that assert_type will work.

Is it safe to assume that I have to upgrade from 3.4.2 to 3.6 or 3.7?

--
mohammed

**Comment by hajee** [comment]
yes you are right
