### ISSUE TITLE
Dependency list

### ISSUE THREAD

**Issue by LiamLeane** [hajee/ora_rac#4]
Fantastic module, saved me days of work. The dependencies listed on the page (and in the metadata) are incomplete though, including dependencies of dependencies needed these to get it to run;

* hajee/easy_type
* fiddyspence/sleep
* hajee/partition
* biemond/oradb
* hajee/hacks
* puppetlabs/firewall
* hajee/oracle
* ripienaar/module_data

The last one is the only one which is non-obvious, it will just throw hiera lookup errors so unless you are familiar with the module data easy to miss.

**Comment by hajee** [comment]
thanks for reporting this.
